export const CARD_IMAGES: Record<string, string> = {
  yeti: '/cards/yeti_iho.png',
  villager: '/cards/villageois_samuil.png',
  troll: '/cards/troll_nufo.png',
  triton: '/cards/triton_ohiorahu.png',
  treant: '/cards/treant_lugajo.png',
  succubus: '/cards/succube_tnuho.png',
  siren: '/cards/sirene_oua.png',
  scientist: '/cards/scientifique_nitglilt.png',
  king: '/cards/roi_pil_jadr.png',
  queen: '/cards/reine_pil_jadr.png',
  princess_strict: '/cards/princesse_stricte.png',
  princess_proud: '/cards/princesse_orgueilleuse.png',
  princess_oppressive: '/cards/princesse_oppressante.png',
  princess_disappointed: '/cards/princesse_decue.png',
  princess_curious: '/cards/princesse_curieuse.png',
  princess_angry: '/cards/princesse_colerique.png',
  princess_attentive: '/cards/princesse_attentive.png',
  princess_ambitious: '/cards/princesse_ambitieuse.png',
  worker: '/cards/ouvrier_jadrlald.png',
  ogre: '/cards/ogre_pfozet.png',
  minotaur: '/cards/minotaure_runuprnu.png',
  merchant_lugajo: '/cards/marchand_lugajo.png',
  merchant_lorino: '/cards/marchand_lorino.png',
  mage: '/cards/mage_kogu.png',
  librarian: '/cards/libraire_voa.png',
  engineer: '/cards/ingenieur_nitglilt.png',
  ifrit: '/cards/ifrit_voa.png',
  harpy: '/cards/harpie_ounaulu.png',
  warrior: '/cards/guerrier_runu.png',
  healer: '/cards/guerisseur_keel_jadr.png',
  goblin: '/cards/gobelin_folg.png',
  giant: '/cards/geant_gojo.png',
  proud_knight: '/cards/fier_chevalier_torun.png',
  fairy: '/cards/fee_talz.png',
  gravedigger: '/cards/faussoyeur_vijo.png',
  druid: '/cards/druide_lorino.png',
  demon_pfozet: '/cards/demon_pfozet.png',
  demon_josu: '/cards/demon_josu.png',
  knight_runu: '/cards/chevalier_runu.png',
  knight_gojo: '/cards/chevalier_gojo.png',
  bibliothecary: '/cards/bibliothecaire_vijo.png',
  atlante: '/cards/atlante_torun.png',
  assassin: '/cards/assassin_wjoh_jadr.png',
  angel: '/cards/ange_ounaulu.png',
  friend: '/cards/ami_jadrlald.png',
  regeneration: '/cards/regeneration.png',
  burn: '/cards/brulure.png',
  fireball: '/cards/boule_de_feu.png',
  electrocution: '/cards/electrocution.png',
  lightning: '/cards/foudroiement.png',
  death: '/cards/mort.png',
  barrier: '/cards/barriere.png',
  choice_of_soul: '/cards/choix_ame.png',
  concentration: '/cards/concentration.png',
  counter_magic: '/cards/contre_magie.png',
  immunity: '/cards/immunite.png',
  manipulation: '/cards/manipulation.png',
  restriction: '/cards/restriction.png',
  life: '/cards/vie.png',
  default: '/cards/back.png',
};

export const EFFECT_ACCENT: Record<string, { from: string; border: string }> = {
  default: { from: 'from-slate-950/80', border: 'border-slate-500' },
  death: { from: 'from-slate-950/90', border: 'border-slate-200' },
  burn: { from: 'from-orange-950/80', border: 'border-orange-500' },
  fireball: { from: 'from-red-950/80', border: 'border-red-500' },
  electrocution: { from: 'from-blue-950/80', border: 'border-blue-400' },
  lightning: { from: 'from-yellow-950/80', border: 'border-yellow-300' },
  regeneration: { from: 'from-emerald-950/80', border: 'border-emerald-400' },
  barrier: { from: 'from-sky-950/80', border: 'border-sky-400' },
  choice_of_soul: { from: 'from-amber-950/80', border: 'border-amber-400' },
  concentration: { from: 'from-indigo-950/80', border: 'border-indigo-400' },
  counter_magic: { from: 'from-cyan-950/80', border: 'border-cyan-400' },
  immunity: { from: 'from-violet-950/80', border: 'border-violet-400' },
  manipulation: { from: 'from-purple-950/80', border: 'border-purple-400' },
  restriction: { from: 'from-slate-900/80', border: 'border-slate-400' },
  life: { from: 'from-rose-950/80', border: 'border-rose-400' },
};

export const EFFECT_EMOJI: Record<string, string> = {
  default: '✨',
  yeti: '🦣',
  villager: '🏡',
  troll: '👹',
  triton: '🌊',
  treant: '🌳',
  succubus: '😈',
  siren: '🧜',
  scientist: '🔬',
  king: '🤴',
  queen: '👑',
  princess_strict: '👸',
  princess_proud: '👸',
  princess_oppressive: '👸',
  princess_disappointed: '👸',
  princess_curious: '👸',
  princess_angry: '👸',
  princess_attentive: '👸',
  princess_ambitious: '👸',
  worker: '🛠️',
  ogre: '💪',
  minotaur: '🐂',
  merchant_lugajo: '💰',
  merchant_lorino: '💰',
  mage: '🧙',
  librarian: '📚',
  engineer: '⚙️',
  ifrit: '🔥',
  harpy: '🪽',
  warrior: '⚔️',
  healer: '💚',
  goblin: '👺',
  giant: '🗿',
  proud_knight: '🛡️',
  fairy: '🧚',
  gravedigger: '⚰️',
  druid: '🌿',
  demon_pfozet: '😈',
  demon_josu: '😈',
  knight_runu: '🐴',
  knight_gojo: '🐴',
  bibliothecary: '📖',
  atlante: '🌊',
  assassin: '🗡️',
  angel: '👼',
  friend: '🤝',
  regeneration: '🌱',
  burn: '🔥',
  fireball: '🔴',
  electrocution: '⚡',
  lightning: '🌩️',
  death: '💀',
  barrier: '🛡️',
  choice_of_soul: '✨',
  concentration: '🧘',
  counter_magic: '🌀',
  immunity: '✴️',
  manipulation: '🎭',
  restriction: '⛓️',
  life: '❤️',
};
